name=input("enter the name: ")
age=input("enter the age: ")
course=input("enter the course: ")
college=input("enter the college: ")
print("\nStudent Information")
print("-----------")
print(name)
print(age)
print(course)
print(college)
